name: Go fmt
on:
  - pull_request
  - push


jobs:
  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - name: Check code formatting using gofmt
        uses: Jerome1337/gofmt-action@v1.0.4
